language: ruby

rvm:
  - 2.1.7
  - 2.2.3
  - 2.3.0

gemfile:
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.2.gemfile

matrix:
  exclude:
    - rvm: 2.1.7
      gemfile: gemfiles/activerecord_5.0.gemfile
    - rvm: 2.1.7
      gemfile: gemfiles/activerecord_5.1.gemfile
    - rvm: 2.1.7
      gemfile: gemfiles/activerecord_5.2.gemfile

script: bundle exec rspec spec

sudo: false
