language: ruby

rvm:
  - 2.5
  - 2.6

gemfile:
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_6.0.gemfile

script: bundle exec rspec spec

sudo: false
