language: ruby

rvm:
  - 2.1.7
  - 2.2.3
  - 2.3.0
  - 2.4.6
  - 2.5.5
  - 2.6.3

gemfile:
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_6.0.gemfile

matrix:
  exclude:
    - rvm: 2.1.7
      gemfile: gemfiles/activerecord_5.0.gemfile
    - rvm: 2.1.7
      gemfile: gemfiles/activerecord_5.1.gemfile
    - rvm: 2.1.7
      gemfile: gemfiles/activerecord_5.2.gemfile
    - rvm: 2.1.7
      gemfile: gemfiles/activerecord_6.0.gemfile
    - rvm: 2.2.3
      gemfile: gemfiles/activerecord_6.0.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/activerecord_6.0.gemfile
    - rvm: 2.4.6
      gemfile: gemfiles/activerecord_6.0.gemfile

script: bundle exec rspec spec

sudo: false
